FROM envoyproxy/envoy:v1.9.0

RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -

RUN apt-get update && apt-get -q install -y apt-transport-https
RUN echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list

RUN apt-get update && apt-get -q install -y curl logrotate inetutils-ping less filebeat nano

COPY filebeat.yml /etc/filebeat/filebeat.yml

# looks like new envoy.log file does not show up when rotating, how does envoy handle log-file fd?
# COPY envoy.logrotate /etc/logrotate.d/envoy
# RUN chmod 644 /etc/logrotate.d/envoy
CMD service filebeat start && /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy --log-path /var/log/envoy.log
